
name: Secureflow Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello, world!"

    

  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (full history + JSON report)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            ghcr.io/gitleaks/gitleaks:latest \
            detect \
            --source="/repo" \
            --log-opts="--all" \
            --report-format=json \
            --report-path="/repo/gitleaks-report.json"
      
      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json