
name: Secureflow Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello, world!"

  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for full git history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --log-opts="--all" --verbose